package com.bean;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2017-4-12 21:56:26 by Hibernate Tools 3.4.0.CR1

/**
 * TSurvey generated by hbm2java
 */
@Entity
@Table(name="t_survey")
public class SurveyBean implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer surveyId;
	private String surveyTitle;
	private String surveyType;
	private String voters;
	private String lookPeople;
	private String beginTime;
	private String endTime;

	public SurveyBean() {
	}

	public SurveyBean(String surveyTitle, String surveyType, String voters,
			String lookPeople, String beginTime, String endTime) {
		this.surveyTitle = surveyTitle;
		this.surveyType = surveyType;
		this.voters = voters;
		this.lookPeople = lookPeople;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public Integer getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	public String getSurveyTitle() {
		return this.surveyTitle;
	}

	public void setSurveyTitle(String surveyTitle) {
		this.surveyTitle = surveyTitle;
	}

	public String getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(String surveyType) {
		this.surveyType = surveyType;
	}

	public String getVoters() {
		return this.voters;
	}

	public void setVoters(String voters) {
		this.voters = voters;
	}

	public String getLookPeople() {
		return this.lookPeople;
	}

	public void setLookPeople(String lookPeople) {
		this.lookPeople = lookPeople;
	}

	public String getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

}
