package com.bean;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 2017-4-12 21:56:26 by Hibernate Tools 3.4.0.CR1

/**
 * TSurveyOptions generated by hbm2java
 */
@Entity
@Table(name="t_survey_options")
public class SurveyOptionsBean implements java.io.Serializable {
	@EmbeddedId
	private SurveyOptionsIdBean id;
	private String number;
	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public SurveyOptionsBean() {
	}

	public SurveyOptionsBean(SurveyOptionsIdBean id) {
		this.id = id;
	}

	public SurveyOptionsIdBean getId() {
		return this.id;
	}

	public void setId(SurveyOptionsIdBean id) {
		this.id = id;
	}

}
