package com.bean;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 2017-4-12 21:56:26 by Hibernate Tools 3.4.0.CR1

/**
 * TSurveyOptionsId generated by hbm2java
 */
@Embeddable
public class SurveyOptionsIdBean implements java.io.Serializable {
	@Column(name="survey_id")
	private Integer surveyId;
	private String options;


	public SurveyOptionsIdBean() {
	}

	public SurveyOptionsIdBean(Integer surveyId, String options) {
		this.surveyId = surveyId;
		this.options = options;
	}

	public Integer getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((options == null) ? 0 : options.hashCode());
		result = prime * result
				+ ((surveyId == null) ? 0 : surveyId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SurveyOptionsIdBean other = (SurveyOptionsIdBean) obj;
		if (options == null) {
			if (other.options != null)
				return false;
		} else if (!options.equals(other.options))
			return false;
		if (surveyId == null) {
			if (other.surveyId != null)
				return false;
		} else if (!surveyId.equals(other.surveyId))
			return false;
		return true;
	}

	


}
